### ISSUE TITLE
@import inlining via filesystem

### ISSUE THREAD

**Issue by paulirish** [codenothing/css-compressor#2]
I believe you've said you support `@import` inlining..

firstly, is that true?  

secondly, is it supported via the CLI? (my research indicates that even on `--mode=full` no @imports are inlined.)

lastly, it wasnt the worst thing in the world but a little bit of docs on the cli would be great (so people know you have it!)

**Comment by codenothing** [comment]
1&2) Must be a misunderstanding, I support @import tags in the compressor, but I don't read the filesystem to pull that css.

3) Very true, I'll add those in after I vamp up the cli script a bit more.

**Comment by paulirish** [comment]
damn. okay.. was a misunderstanding indeed.  is it possible to actually do the read? it's like the one magic thing that's left out of every css compressor i've seen.

_updates ticket title to be for this_

**Comment by codenothing** [comment]
Yea, I can see the use case for this, but it will have to be turned off by default on all modes.

**Comment by codenothing** [comment]
So after giving it some thought, I feel that it doesn't belong inside the compressor itself. It's only goal is string manipulation, and file system access is outside it's scope.

On the other hand, replacing imports with their contents is perfect for the cli script, since that requires you to be interacting with the file system to use it. It can still use some more vigorous testing for corner cases, but should fit whatever needs you have at the moment.

https://github.com/codenothing/css-compressor/commit/450e30abe92c7ee32f0224b2e153271779ab1407
